### ISSUE TITLE
無法使用

### ISSUE THREAD

**Issue by ghongchen** [qqaatw/taipower-ha#2]
您好

感謝您，之前一直在home assistant使用這個元件取得用電資料
但在大約2週前，突然無法使用
試著移除元件並重新安裝
但在新增台電帳號時，均會出現錯誤的帳號或密碼(很確定帳密沒有錯，因為可以從台電app登入)
不知是否是台電有更改什麼導致出現錯誤

**Comment by qqaatw** [comment]
Probably. I don't have time looking into it, sorry.
